---
- name: get toolchain from git
  action: git repo=$git_url/$toolchain_repo dest=$sdk_home version=$toolchain_ver
  notify:
    - make sdk
  tags:
    - git

- name: get headers from git
  action: git repo=$git_url/$headers_repo dest=$sdk_home/SRC/linux-headers-for-nacl version=$headers_ver
  notify:
    - make sdk
  tags:
    - git

- name: get gcc from git
  action: git repo=$git_url/$gcc_repo dest=$sdk_home/SRC/gcc version=$gcc_ver
  notify:
    - make sdk
  tags:
    - git

- name: get binutils from git
  action: git repo=$git_url/$binutils_repo dest=$sdk_home/SRC/binutils version=$binutils_ver
  notify:
    - make sdk
  tags:
    - git

- name: get glibc from git
  action: git repo=$git_url/$glibc_repo dest=$sdk_home/SRC/glibc version=$glibc_ver
  notify:
    - make sdk
  tags:
    - git

- name: get newlib from git
  action: git repo=$git_url/$newlib_repo dest=$sdk_home/SRC/newlib version=$newlib_ver
  notify:
    - make sdk
  tags:
    - git

- name: get zerovm from git
  action: git repo=$git_url/$zerovm_repo dest=$zerovm_home version=$zerovm_ver;
  tags:
    - git
  notify: 
    - make zerovm

- name: get validator from git
  action: git repo=$git_url/$validator_repo dest=$zerovm_home/valz version=$validator_ver;
  tags:
    - git
  notify:
    - make validator


- name: get zrt from git
  action: git repo=$git_url/$zrt_repo dest=$zrt_home version=$zrt_ver
  tags:
    - git
  notify:
    - make sdk
    - make gtest

- name: get llvm from git
  action: git repo=$git_url/$llvm_repo dest=$sdk_home/llvm version=$llvm_ver
  tags:
    - git
  notify:
    - make llvm

- name: get clang from git
  action: git repo=$git_url/$clang_repo dest=$sdk_home/llvm/tools/clang version=$clang_ver
  tags:
    - git
  notify:
    - make llvm

- name: get binutils from git
  action: git repo=$git_url/$binutils_repo dest=$sdk_home/binutils version=$binutils_ver
  notify:
    - make bfd
  tags:
    - git

- name: get zerovm-llvm from git
  action: git repo=$zerovm_llvm_url dest=$sdk_home/zerovm-llvm
  notify:
    - make libjit
    - make libzdl
  tags:
    - git