---
- hosts: build
  user: vagrant
  sudo: True
  gather_facts: False
  vars_files:
    - ../global_vars.yaml

  tasks:
    - include: ../tasks/prereq_install.yaml

- hosts: build
  user: vagrant
  sudo: False
  gather_facts: False
  vars_files:
    - ../global_vars.yaml

  tasks:
    - include: ../tasks/build-sdk.yaml

  handlers:
    - include: ../handlers/build-sdk.yaml

